import { PrismaClient } from "@prisma/client/";
const prisma = new PrismaClient();

const exercises: {
  id?: string;
  name: string;
  description?: string | null;
  videos?: string[];
  images?: string[];
  i18?: [];
  userId: string;
}[] = [
  {
    name: "ab-wheel",
  },
  {
    name: "Aerobics",
  },
  { name: "arnolD press" },
  { name: "around The-world" },
  { name: "back-extension" },
  { name: "back-extension-machine" },
  { name: "ball-slams" },
  { name: "battle ropes" },
  { name: "bench dip" },
  { name: "bench press-barbell" },
  { name: "bench press cable" },
  { name: "bench press dumbbell" },
  { name: "bench press machine" },
  { name: "bench press close grip barbell" },
  { name: "bench press wide grip barbell" },
  { name: "bent over row one arm" },
  { name: "bent over row band" },
  { name: "bent over row barbell" },
  { name: "bent over row dumbbell" },
  { name: "bent over row underhand barbell" },
  { name: "bicep curl barbell" },
  { name: "bicep curl cable" },
  { name: "bicep curl dumbbell" },
  { name: "bicep curl machine" },
  { name: "bicycle crunch" },
  { name: "box jump" },
  { name: "box squat" },
  { name: "bulgarian split squat" },
  { name: "burpee" },
  { name: "cable crossover" },
  { name: "cable crunch" },
  { name: "cable kickback" },
  { name: "cable pull through" },
  { name: "cable twist" },
  { name: "calf press on leg press" },
  { name: "calf press on seated leg press" },
  { name: "chest dip" },
  { name: "chest dip assisted" },
  { name: "chest fly" },
  { name: "chest fly band" },
  { name: "chest fly dumbbell" },
  { name: "chest press band" },
  { name: "chest press machine" },
  { name: "chin up" },
  { name: "chin up assisted" },
  { name: "clean barbell" },
  { name: "clean and jerk barbell" },
  { name: "climbing" },
  { name: "concentration curl dumbbell" },
  { name: "cross body crunch" },
  { name: "crunch" },
  { name: "crunch machine" },
  { name: "crunch stability ball" },
  { name: "cycling" },
  { name: "cycling indoor" },
  { name: "deadlift band" },
  { name: "deadlift machine" },
  { name: "deadlift high pull" },
  { name: "deadlift barbell" },
  { name: "deadlift dumbbell" },
  { name: "decline bench press dumbbell" },
  { name: "decline bench press machine" },
  { name: "decline crunch" },
  { name: "deficit deadlift barbell" },
  { name: "elliptical machine" },
  { name: "face pull" },
  { name: "flat knee raise" },
  { name: "flat leg raise" },
  { name: "floor press barbell" },
  { name: "front raise band" },
  { name: "front raise barbell" },
  { name: "front raise cable" },
  { name: "front raise dumbbell" },
  { name: "front raise plate" },
  { name: "front squat barbell" },
  { name: "glute ham raise" },
  { name: "glute kickback machine" },
  { name: "goblet squat kettlebell" },
  { name: "good mornging barbell" },
  { name: "hack squat" },
  { name: "hack squat barbell" },
  { name: "hammer curl band" },
  { name: "hammer curl cable" },
  { name: "hammer curl dumbbell" },
  { name: "handstand push up" },
  { name: "hang clean barbell" },
  { name: "hang snatch barbell" },
  { name: "hanging knee raise" },
  { name: "hanging leg raise" },
  { name: "hanging knee raise" },
  { name: "high knee skips" },
  { name: "hiking" },
  { name: "hip abductor machine" },
  { name: "hip adductor machine" },
  { name: "hip thrust barbell" },
  { name: "hip thrust bodyweight" },
  { name: "incline bench press barbell" },
  { name: "incline bench press cable" },
  { name: "incline bench press dumbbell" },
  { name: "incline bench press machine" },
  { name: "incline chest fly dumbbell" },
  { name: "incline chest press machine" },
  { name: "incline curl dumbbell" },
  { name: "incline row dumbbell" },
  { name: "inverted row bodyweight" },
  { name: "iso lateral chest press" },
  { name: "iso lateral row machine" },
  { name: "jackknife sit up" },
  { name: "jump rope" },
  { name: "jump shrug barbell" },
  { name: "jump squat" },
  { name: "jumping jack" },
  { name: "kettlebell swing" },
  { name: "kettlebell turkish get up" },
  { name: "kipping pull up" },
  { name: "knee raise" },
  { name: "kneeling pulldown band" },
  { name: "knees to elbows" },
  { name: "lat pulldown cable" },
  { name: "lat pulldown machine" },
  { name: "lat pulldown single arm" },
  { name: "lat pulldown underhand band" },
  { name: "lat pulldown underhand cable" },
  { name: "lat pulldown wide grip cable" },
  { name: "lateral box jump" },
  { name: "lateral raise band" },
  { name: "lateral raise cable" },
  { name: "lateral raise dumbbell" },
  { name: "lateral raise machine" },
  { name: "leg extension machine" },
  { name: "leg press" },
  { name: "lunge barbell" },
  { name: "lunge bodyweight" },
  { name: "lunge dumbbell" },
  { name: "lying leg curl" },
  { name: "mountain climber" },
  { name: "muscle up" },
  { name: "oblique crunch" },
  { name: "overhead press barbell" },
  { name: "overhead press cable" },
  { name: "overhead press dumbbell" },
  { name: "overhead press machine" },
  { name: "overhead squat barbell" },
  { name: "pec deck machine" },
  { name: "pendlay row" },
  { name: "pistol squat" },
  { name: "plank" },
  { name: "power clean" },
  { name: "power snatch barbell" },
  { name: "preacher curl barbell" },
  { name: "preacher curl dumbbell" },
  { name: "preacher curl machine" },
  { name: "press under barbell" },
  { name: "pull up" },
  { name: "pull up assisted" },
  { name: "pull up band" },
  { name: "pullover machine" },
  { name: "push press" },
  { name: "push up" },
  { name: "push up band" },
  { name: "push up knees" },
].map((exercise) => {
  return {
    ...exercise,
    name: exercise.name.replace(/\s/g, "-").toLowerCase(),
    userId: "62dc13e3a5a78cb9fc4ca059",
    visible: false,
  };
});

async function main() {
  Promise.all([
    await prisma.exercise.deleteMany(),
    ...exercises.map(async (exercise) => {
      await prisma.exercise.create({
        data: {
          ...exercise,
        },
      });
    }),
  ]);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
